{
 "title": "SurgePay - Kafka Messaging Dashboard",
 "tags": [
  "surgepay",
  "kafka"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages Published Rate (by Event Type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(events_published_total[1m])) by (eventType)",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  {
   "title": "Messages Consumed Rate (by Consumer Group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(events_consumed_total[1m])) by (consumer, eventType)",
     "legendFormat": "{{consumer}} - {{eventType}}"
    }
   ]
  },
  {
   "title": "Producer Latency (Average ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(publish_duration_ms_sum[5m])) by (eventType) / sum(rate(publish_duration_ms_count[5m])) by (eventType)",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  {
   "title": "Publish Success Rate vs failure Rate (ratio)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(events_published_total[1m])) by (service)",
     "legendFormat": "Successes ({{service}})"
    },
    {
     "expr": "sum(rate(publish_failures_total[1m])) by (service)",
     "legendFormat": "Failures ({{service}})"
    }
   ]
  },
  {
   "title": "Kafka Topic Throughput (Total Msg Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(events_published_total[1m]))",
     "legendFormat": "Total Message Ingestion Rate"
    }
   ]
  },
  {
   "title": "Publish Success Percentage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(events_published_total[1m])) / (sum(rate(events_published_total[1m])) + sum(rate(publish_failures_total[1m])) + 0.0001) * 100",
     "legendFormat": "Success %"
    }
   ]
  }
 ]
}