export enum DomainErrorCode {
  DUPLICATE_PAYMENT_REFERENCE = 'DUPLICATE_PAYMENT_REFERENCE',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_COMPLETED = 'PAYMENT_ALREADY_COMPLETED',
  INVALID_PAYMENT_STATE_TRANSITION = 'INVALID_PAYMENT_STATE_TRANSITION',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ALREADY_PAID = 'ORDER_ALREADY_PAID',
  ORDER_AMOUNT_MISMATCH = 'ORDER_AMOUNT_MISMATCH',
  FRAUD_REJECTED = 'FRAUD_REJECTED',
  PAYMENT_VALIDATION_FAILED = 'PAYMENT_VALIDATION_FAILED',
}
